FROM node:24-alpine

WORKDIR /usr/src/app

RUN apk add --no-cache tini openssl

COPY package*.json ./
COPY prisma ./prisma

RUN npm install

RUN npx prisma generate

EXPOSE 3000

ENTRYPOINT ["/sbin/tini", "--"]
CMD ["npm", "run", "start:dev"]